spring.application.name=EvergreenServer
server.port=8080
server.host='0.0.0.0'
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security=DEBUG


# Database Config

spring.datasource.username=evergreen_test_user
spring.datasource.password=Google@123
spring.datasource.url=jdbc:postgresql://localhost:5432/evergreen_test_db
spring.datasource.driverClassName=org.postgresql.Driver

# avoid conflitcs with liquibase or flyway 
spring.jpa.hibernate.ddl-auto=none 

spring.profiles.active=dev
spring.liquibase.contexts=dev


# spring.flyway.locations=classpath:/db/{vendor}/migrations
# spring.flyway.lock-retry-count=10
# spring.flyway.enabled=true

spring.liquibase.change-log=classpath:db/liquibase/db.changelog-master.yml
# /home/ahmedkabeer/Desktop/development/learning/java/EvergreenServer/src/main/resources/db/liquibase/db.changelog-master.yml
spring.liquibase.enabled=true

# spring batch

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never


# misc (swagger)
spring.mvc.favicon.enabled=false